#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

GOGS_VERSION=20151110043405

# Munin plugins
MUNIN_PLUGINS="
nginx
"

# Exit if any commands fail
set -o errexit

echo "* Configuring image specific packages.";

echo "* Download and unzip gogs"
curl http://tmp.cyber-tec.org/dev/gogs.${GOGS_VERSION}.tar.gz | gtar xz -C /opt/gogs --strip-components=1

echo "* Create gogs user and permissions"
useradd -m -c "Gogs - Go Git Service" -s /opt/local/bin/bash -d /opt/gogs git
chown -R gogs:other /opt/gogs

echo "* Create ssl folder for nginx"
mkdir /opt/local/etc/nginx/ssl

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
