#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
nginx
"

# Exit if any commands fail
set -o errexit

echo "* Configuring image specific packages.";

echo "* Create gogs log folder"
mkdir -p /var/log/gogs

echo "* Create gogs user and permissions"
useradd -m -c "Gogs - Go Git Service" -d /opt/gogs git
chown -R gogs:other /opt/gogs

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
